trainer: energy

dataset:
  - src: data/lmdb/train_unary_47_binary_399
    normalize_labels: True
    target_mean: 0.09554652282470219
    target_std: 0.04313544930263222
  - src: data/lmdb/val_binary_10
    normalize_labels: True
    target_mean: 0.09554652282470219
    target_std: 0.04313544930263222


logger: tensorboard

task:
  dataset: single_point_lmdb
  description: "Density prediction from structure."
  type: regression
  metric: mae
  labels:
    - relaxed energy #not used
  strict_load: False

model:
  name: scn
  num_interactions: 5
  hidden_channels: 256
  sphere_channels: 128
  sphere_channels_reduce: 128
  num_sphere_samples: 128
  num_basis_functions: 128
  distance_function: "gaussian"
  max_num_neighbors: 12
  cutoff: 6.0
  lmax: 8
  num_bands: 2
  num_taps: 4
  use_grid: True
  regress_forces: False
  use_pbc: True
  basis_width_scalar: 2.0
  otf_graph: False

optim:
  batch_size: 175
  eval_batch_size: 175
  num_workers: 4
  lr_initial: 0.0004
  optimizer: AdamW
  optimizer_params: {"amsgrad": True}
  eval_every: 5000
  lr_gamma: 0.3
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 20000
    - 30000
    - 40000
  warmup_steps: 1000
  warmup_factor: 0.2
  max_epochs: 10
  force_coefficient: 100
  energy_coefficient: 2
  clip_grad_norm: 100
  ema_decay: 0.999
  loss_energy: mae
  loss_force: l2mae

slurm:
  qos: scavenger
  account: scavenger
  partition: scavenger
  time: 2-00:00:00
  gres: gpu:rtxa5000:1
  mem: 32G
